# Generated by Django 4.1.7 on 2023-05-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category_alter_product_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_slug',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category_slug',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
